#!/bin/sh

bspc config border_width         2
bspc config window_gap          24
bspc config top_padding		36

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-2 -d 6 7 8 9 10

bspc config normal_border_color '#282828'
bspc config focused_border_color '#d5c4a1'
bspc config presel_feedback_color '#d79921'
bspc config normal_sticky_border_color '#1d2021'
bspc config focused_sticky_border_color '#d5c4a1'
bspc config urgent_border_color '#cc241d'

xrdb ~/.Xresources
sxhkd &
compton -f &
/home/jon/.config/bin/startup.sh 
